### PR TITLE
Switch API level to 610

### PR DESCRIPTION
**Pull request by nickva**
There were some changes that had to be accounted for:

 * Cluster is gone, so cluster futures, resources, etc were removed

 * Create database returns a database object not future, so database future
   type is removed.

 * It's possible to use json tracing format on the client, so added that
   netowrk option.

### CODE REVIEW

**Comment by nickva** [comment]
EUnit tests pass

```
Compiled test/erlfdb_02_anon_fdbserver_test.erl
======================== EUnit ========================
erlfdb_05_get_next_tx_id_test: get_tx_id_test (module 'erlfdb_05_get_next_tx_id_test')...[2.439 s] ok
module 'erlfdb_float'
module 'erlfdb'
module 'erlfdb_tuple'
  erlfdb_tuple: fdb_vectors_test...ok
  erlfdb_tuple: bindingstester_discoveries_test...ok
  [done in 0.006 s]
erlfdb_01_basic_test: load_test (module 'erlfdb_01_basic_test')...ok
module 'erlfdb_util'
module 'erlfdb_hca'
module 'erlfdb_nif'
module 'erlfdb_subspace'
module 'erlfdb_02_anon_fdbserver_test'
  erlfdb_02_anon_fdbserver_test: basic_init_test...ok
  erlfdb_02_anon_fdbserver_test: basic_open_test...ok
  erlfdb_02_anon_fdbserver_test: get_db_test...ok
  erlfdb_02_anon_fdbserver_test: get_set_get_test...[0.016 s] ok
  erlfdb_02_anon_fdbserver_test: get_empty_test...[0.019 s] ok
  [done in 0.050 s]
module 'erlfdb_directory'
module 'erlfdb_key'
=======================================================
  All 9 tests passed.
```

**Comment by nickva** [comment]
Fabric tests for CouchDB pass as well

```
 $ make eunit apps=fabric

=======================================================
  All 128 tests passed.
Cover analysis: /Users/nvatama/asf/src/fabric/.eunit/index.html
```

**Review by davisp — APPROVED** [review]
Excellent. This is pretty much exactly what I was expecting this too look like.

However, please hold off on merging while I go back and relearn how to run the bindings tester from FoundationDB against this change. I'll open another PR that documents how to do that for future PRs of this nature.

**Comment by nickva** [comment]
Ran bindings tester

```
$ PYTHONPATH=/Users/nvatama/src/foundationdb/build/bindings/python ./bindingtester.py --cluster-file /usr/local/etc/foundationdb/fdb.cluster --num-ops 10000 --test-name api erlang

Creating test at API version 610
Generating api test at seed 432920150 with 10000 op(s) and 1 concurrent tester(s)...

Inserting test into database...

Running tester '/Users/nvatama/asf/src/erlfdb/test/tester.es test_spec 610 /usr/local/etc/foundationdb/fdb.cluster'...

Reading results from '('tester_output', 'workspace')'...
Reading results from '('tester_output', 'stack')'...


Test with seed 432920150 and concurrency 1 had 0 incorrect result(s) and 0 error(s) at API version 610
Completed api test with random seed 432920150 and 10000 operations

```

**Pull request merged**
